// unit_messages.cpp — C++ session message builders vs golden bytes built by
// the Python reference builders (probe5 / probe7 / rbx_client).
//
// The goldens live in tests/vectors/msgs/ and are generated by
// tools/gen_vectors.py; tools/msg_parity.py independently compares the same
// C++ builders against the Python builders at runtime — this suite pins the
// bytes themselves, so a drift fails fast without the Python toolchain.
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include "session.h"

#include <nlohmann/json.hpp>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using nlohmann::json;

namespace {

json load_join() {
    std::ifstream f(fs::path(REPO_ROOT) / "run" / "join_full.json");
    REQUIRE(f);
    json j;
    f >> j;
    return j;
}

std::vector<uint8_t> slurp(const fs::path& p) {
    std::ifstream f(p, std::ios::binary);
    REQUIRE(f);
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(f),
                                std::istreambuf_iterator<char>());
}

int ticket_version(const std::string& ct) {
    if (ct.empty())
        return 0;
    return std::stoi(ct.substr(ct.rfind(';') + 1));
}

} // namespace

TEST_CASE("early-auth payload") {
    const json j = load_join();
    const json& js = j.at("joinScript");
    const std::string ct = js.value("ClientTicket", "");
    const auto got = rbx::msgs::earlyAuth(ct, ticket_version(ct));
    CHECK(got == slurp(fs::path(REPO_ROOT) / "tests" / "vectors" / "msgs" / "earlyauth.bin"));
}

TEST_CASE("0x8A message") {
    const json j = load_join();
    const auto got = rbx::msgs::build8A(j.at("joinScript"));
    CHECK(got == slurp(fs::path(REPO_ROOT) / "tests" / "vectors" / "msgs" / "m8a.bin"));
}

TEST_CASE("0x90 message") {
    const json j = load_join();
    std::string err;
    const auto got = rbx::msgs::build90(j.at("joinScript"), j.value("reply", json::object()),
                                        std::string(REPO_ROOT) + "/py/captures", &err);
    REQUIRE(err.empty());
    CHECK(got == slurp(fs::path(REPO_ROOT) / "tests" / "vectors" / "msgs" / "m90.bin"));
}

TEST_CASE("0x92 message structure") {
    // 0x92 carries a random nonce — no golden bytes; check the structure
    // instead (mirrors the structural check in tools/msg_parity.py).
    constexpr uint64_t M64 = 0xFFFFFFFFFFFFFFFFull;
    constexpr int64_t V9 = 0x63E25F26;

    const auto got = rbx::msgs::build92();
    REQUIRE_FALSE(got.empty());
    CHECK(got[0] == 0x92);

    uint64_t v = 0;
    int shift = 0;
    size_t i = 1;
    for (; i < got.size(); ++i) {
        const uint8_t b = got[i];
        v |= uint64_t(b & 0x7F) << shift;
        shift += 7;
        if (!(b & 0x80))
            break;
    }
    REQUIRE(i < got.size()); // terminated LEB
    const uint64_t x = ((v >> 1) ^ (v & 1 ? M64 : 0)) & M64;
    const uint64_t v8 = x >> 32;
    CHECK(x == (((v8 << 32) | (v8 ^ uint64_t(V9))) & M64));
}
